spring:
  application:
    name=student-api
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 9951608360
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  


